application: omezacycle
version: 1
runtime: python
api_version: 1

handlers:
- url: /public
  static_dir: public

- url: /periods/?.*
  script: periods.py

- url: /archive
  script: archive.py

- url: /.*
  script: omeza.py

skip_files: |
  ^(.*/)?(
  (app\.yaml)|
  (app\.yml)|
  (index\.yaml)|
  (index\.yml)|
  (#.*#)|
  (.*~)|
  (.*\.py[co])|
  (.*/RCS/.*)|
  (\..*)|
  (goog)|
  )$
